# Generated by Django 3.2.3 on 2021-06-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCasa',
            fields=[
                ('idHogar', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo casa')),
                ('nombreHogar', models.CharField(max_length=15, verbose_name='Nombre del tipo de casa')),
            ],
        ),
    ]
