# Generated by Django 3.2.3 on 2021-06-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipocasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='tipocasa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipocasa'),
        ),
    ]
